- name: Install PHP and required extensions
  become: true
  apt:
    name: "{{ item }}"
    state: latest
  loop:
    - php-fpm              # Main PHP package
    - php-mysql           # MySQL support for PHP




- name: Add the configuration file
  become: true
  template:
     src: conf.php.j2
     dest: /etc/nginx/sites-enabled/php



# - name: Copy PHP info file
#   become: true
#   template:
#     src: info.php.j2
#     dest: /var/www/html/index.php
